from __future__ import annotations

from io import BytesIO
from typing import Iterable

import pandas as pd
from pptx import Presentation
from pptx.enum.shapes import PP_PLACEHOLDER


def clean_text(value: object) -> str:
    text = " ".join(str(value or "").replace("\n", " ").split()).strip()
    if text.lower() in {"nan", "none", "null"}:
        return ""
    return text


def is_disclaimer(text: str) -> bool:
    lowered = text.lower()
    return (
        "this report was generated by displayr ai" in lowered
        or "ai can make mistakes" in lowered
        or lowered in {"background"}
    )


def is_admin_slide(title: str, body: str) -> bool:
    combined = f"{title} {body}".lower()
    return (
        "sample description:" in combined
        or "research agent report" in combined
        or "no background has been provided" in combined
    )


def placeholder_type(shape):
    try:
        return shape.placeholder_format.type
    except Exception:
        return None


def iter_shape_text(shape) -> Iterable[str]:
    if hasattr(shape, "text") and clean_text(shape.text):
        text = clean_text(shape.text)
        if not is_disclaimer(text):
            yield text

    if getattr(shape, "has_table", False):
        for row in shape.table.rows:
            cells = [clean_text(cell.text) for cell in row.cells if clean_text(cell.text)]
            if cells:
                yield " | ".join(cells)

    if getattr(shape, "has_chart", False):
        chart = shape.chart
        if chart.has_title:
            title = clean_text(chart.chart_title.text_frame.text)
            if title:
                yield title
        for series in chart.series:
            name = clean_text(getattr(series, "name", ""))
            if name:
                yield f"Chart series: {name}"

    if getattr(shape, "shape_type", None) == 6:
        for grouped_shape in shape.shapes:
            yield from iter_shape_text(grouped_shape)


def slide_title_and_body(texts: list[str]) -> tuple[str, str]:
    if not texts:
        return "PowerPoint slide", ""
    title = texts[0]
    body_parts = []
    for text in texts[1:]:
        if text and text not in body_parts:
            body_parts.append(text)
    if not body_parts:
        body_parts = [title]
    return title, " ".join(body_parts)


def read_pptx_insights(uploaded_file) -> pd.DataFrame:
    uploaded_file.seek(0)
    prs = Presentation(BytesIO(uploaded_file.read()))
    rows = []

    for slide_index, slide in enumerate(prs.slides, start=1):
        title = ""
        texts = []
        for shape in slide.shapes:
            text = clean_text(getattr(shape, "text", ""))
            if placeholder_type(shape) == PP_PLACEHOLDER.TITLE and text and not is_disclaimer(text):
                title = text
                continue
            for text in iter_shape_text(shape):
                if text and text not in texts:
                    texts.append(text)

        if title:
            body_parts = [text for text in texts if text != title and not is_disclaimer(text)]
            body = " ".join(body_parts)
        else:
            title, body = slide_title_and_body([text for text in texts if not is_disclaimer(text)])

        if len(body.split()) < 4:
            continue
        if is_admin_slide(title, body):
            continue

        evidence_text = body[:260]
        rows.append(
            {
                "insight_id": f"PPT-S{slide_index:02d}",
                "theme": title[:90],
                "insight_text": body,
                "evidence_note": (
                    f"PowerPoint report evidence from slide {slide_index}: {evidence_text}. "
                    "Verify chart values against source tables before final client use."
                ),
            }
        )

    return pd.DataFrame(rows)
